<script setup lang="ts">
import LoopingVideo from '@/components/common/LoopingVideo.vue';
import architecture from '@/assets/images/architecture.svg'
// import aiagent from '@/assets/video/ai-agent.webm'

const information = [
    {
        title: 'Introduction',
        desc: 'During my time at PatSnap, I was part of a team focused on building AI agents for the materials domain. Our team consisted of myself, working as a full-stack developer, alongside two algorithm engineers. Together, we designed and implemented a standardized workflow and system that enabled our agents to communicate seamlessly with backend services and frontend components.'
    },
    {
        image: true,
        src: architecture
    },
    {
        title: 'My task',
        desc: 'I designed the frontend–backend architecture and workflow, and defined the API contracts. I implemented the frontend layout and pages from scratch, including handling the event-stream output. I also developed components to visualize the data and outputs generated by our AI agents. Due to company ownership and confidentiality restrictions, I’m unable to include images or videos of these components.'
    },
    // {
    //     video: true,
    //     src: aiagent
    // },
]

</script>

<template>
    <div class="fade-in h-full flex flex-col gap-8">
        <div class="text-2xl font-medium bg-[#f8cb46] p-1 px-4 rounded">AI Agents</div>
        <div class="flex gap-8 min-h-0 h-full">
            <div class="h-full overflow-y-scroll grow flex flex-col gap-6 pr-4">
                <div class="flex flex-col gap-2" v-for="i of information" :key="i.title">
                    <template v-if="i.image">
                        <img :src="i.src" />
                    </template>
                    <!-- <template v-if="i.video">
                        <div class="p-12 border-2 rounded-2xl bg-white m-8 brutal-shadow">
                            <LoopingVideo :src="i.src"></LoopingVideo>
                        </div>
                    </template> -->
                    <template v-else>
                        <span class="text-sm accent-text text-gray-800">{{ i.title }}</span>
                        <p class="text-lg text-[#282825]">{{ i.desc }}</p>
                    </template>
                </div>
            </div>
        </div>
    </div>
</template>